# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c474107dc39b80c9b433bfa5e1d329e098c9e858a8b6cc666f4ae61ec09b4e096939e49ced164ea50febd5b51022eb06c6c5f4be4d88c033d25e59db24c69eb2

test:
  secret_key_base: b932256247e095d523b7571bf9f457f471c3de1ddc2bb2115b1abb8d41cbb1057f1300d3b0a64b490b6551d0c238f16d55b472b1797b9a8f08c1d1f72c469eea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
